version: 2.1
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
        environment:
          CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            cd drp-client && npm install
      - run:
          name: npm run-script build (prod)
          command: |
            cd drp-client && npm run-script build
      - run:
          name: npm test
          command: |
            cd drp-client && npm test


